(WIP) Issue #4 Integrate with CentOS CI
minishift/minishift-b2d-iso pull request #19
Opened 2017-01-12 07:37 UTC by budhrg

Fix #4 

Dependent on 'service-job' creation of [centos ci](ci.centos.org) for https://github.com/Minishift/minishift-ci-jobs and https://github.com/minishift/minishift-ci-jobs/pull/3.

2017-01-12 09:30 UTC, hferentschik requested changes

2017-01-12 09:30 UTC, hferentschik commented on centos_ci.sh
> +curl -L https://github.com/docker/machine/releases/download/v0.8.2/docker-machine-`uname -s`-`uname -m` > docker-machine && \
you provision docker-machine and in the Makefile you install it as well? Seems this here is not required

2017-01-12 09:42 UTC, budhrg commented on centos_ci.sh
> +curl -L https://github.com/docker/machine/releases/download/v0.8.2/docker-machine-`uname -s`-`uname -m` > docker-machine && \
Ya @hferentschik , need to remove it. It was previous plan but need to change it to manage binary from Makefile in context of developer's point of view.

2017-01-17 16:28 UTC, budhrg commented
I am merging this ready and needed for CI integration.

2017-01-17 16:28 UTC, merged