Issue #33 #32 Fix gh-release and added release instructions
minishift/minishift-b2d-iso pull request #53
Opened 2017-08-11 11:37 UTC by budhrg

Fix #32  and #33 

cc @hferentschik @LalatenduMohanty 

Please check in Mac.

2017-08-11 11:40 UTC, budhrg commented
I am not able to test in Linux OS too. Getting some `gh-release` specific error locally: 
```
$ make release
go get -u github.com/progrium/gh-release/...
# rm -rf release &&
mkdir -p release
cp /home/budhram/redhat/minishift-b2d-iso/build/minishift-b2d.iso release/
gh-release checksums sha256
/tmp/bashenv.433487048: line 63: syntax error near unexpected token `('
/tmp/bashenv.433487048: line 63: `export BASH_FUNC_module()=$'() {  eval `/usr/bin/modulecmd bash $*`'
/home/budhram/.basher/bash: main: command not found
Makefile:35: recipe for target 'release' failed
make: *** [release] Error 127
```

2017-08-11 14:04 UTC, budhrg commented
Definitely some issue with `gh-release` with its dependency in Windows OS. Probably might be the reason, the author is also not publishing windows artifacts.

```
PS C:\minishift-b2d-iso> make release
go get -u github.com/progrium/gh-release/...
# github.com/progrium/go-basher
C:\gowork\src\github.com\progrium\go-basher\basher.go:52: undefined: RestoreAsset
make: *** [C:\gowork/bin/gh-release] Error 2
```

2017-08-13 18:37 UTC, hferentschik commented on Makefile
> +release: iso $(GOPATH)/bin/gh-release
:+1

2017-08-13 18:38 UTC, hferentschik commented on Makefile
> +	gh-release checksums sha256
+1

2017-08-13 18:38 UTC, hferentschik commented on README.md
> +- Installed [Go](https://en.wikipedia.org/wiki/Go_(programming_language)) with `GOPATH` properly set.
+1

2017-08-13 18:41 UTC, hferentschik commented on README.md
> +### Releasing the ISO
I'll put the releasing part after testing. First you build, then you test and finally you release. I think these are the logical steps.

2017-08-13 18:42 UTC, hferentschik reviewed
Looking ok to me. I'd just switch release and test part. 

Also, while on it, do you mind adding the community part as well?

2017-08-13 18:45 UTC, hferentschik commented
> Definitely some issue with gh-release with its dependency in Windows OS

I don't think this is a a problem for now. For my part I was able to successfully release to my fork.

2017-08-14 05:56 UTC, budhrg commented on README.md
> +### Releasing the ISO
Sure :+1:

2017-08-14 06:27 UTC, budhrg commented
> For my part I was able to successfully release to my fork.

Thanks for testing. I am having some issue (https://github.com/minishift/minishift-b2d-iso/pull/53#issuecomment-321790267) locally so couldn't test with my fork but definitely should work as I didn't change anything `gh-release` specific.

2017-08-14 07:43 UTC, LalatenduMohanty requested changes

2017-08-14 07:43 UTC, LalatenduMohanty commented on README.md
> +- Installed [Go](https://en.wikipedia.org/wiki/Go_(programming_language)) with `GOPATH` properly set.
s/Installed/Install/

2017-08-14 08:07 UTC, hferentschik commented
@LalatenduMohanty, do you mind giving it a try?

2017-08-14 09:59 UTC, hferentschik reviewed
I added some more comments. Basically I am ok with this. Just would like to get another opinion from a Linux machine.

2017-08-14 09:59 UTC, hferentschik commented on README.md
> +- Install [Go](https://en.wikipedia.org/wiki/Go_(programming_language)) with `GOPATH` properly set.
"Install" is a verb, you need a noun to fit this enumeration. 

Working installation of ....

2017-08-14 09:59 UTC, hferentschik commented on README.md
> +## Community
I put community last, but I leave it up to you.

2017-08-14 10:04 UTC, hferentschik approved these changes

2017-08-14 11:01 UTC, LalatenduMohanty commented
@budhrg I have done previous releases on a CentOS VM and it worked fine. But on Fedora this issue exists https://github.com/progrium/gh-release/issues/19

2017-08-14 11:34 UTC, LalatenduMohanty approved these changes
Works for me on CentOS7 https://github.com/LalatenduMohanty/minishift-b2d-iso/releases/tag/v1.1.0

2017-08-14 11:34 UTC, merged

2017-08-14 11:34 UTC, budhrg commented
With my CentOS VM, I am getting exit code 2.
```
$ make release
make release
rm -rf release && mkdir -p release
cp /home/budhram/redhat/minishift-b2d-iso/build/minishift-b2d.iso release/
gh-release checksums sha256
Writing sha256 checksum files...
gh-release create budhrg/minishift-b2d-iso 1.1.0 master v1.1.0
Creating release v1.1.0 from branch master ...
make: *** [release] Error 2

```