issue #70 move the minishift binary to $(BIN_DIR) after extracting
minishift/minishift-b2d-iso pull request #72
Opened 2017-09-27 06:20 UTC by anjannath

2017-09-27 07:12 UTC, brgnepal requested changes

2017-09-27 07:12 UTC, budhrg commented on Makefile
> +MINISHIFT_DIR=$(shell echo $(MINISHIFT_LATEST_URL) | rev | cut -d/ -f1 | cut -c5- | rev)
@anjannath , plz update `11-12` lines with 
```
ARCHIVE_FILE=$(shell echo $(MINISHIFT_LATEST_URL) | cut -d/ -f9-11)
MINISHIFT_UNTAR_DIR=$(shell echo $(ARCHIVE_FILE) | sed 's/.tgz//')
```

2017-09-27 07:12 UTC, budhrg commented on Makefile
> +	@echo "Moving minishift binary to $(BIN_DIR)"
Update line `42` with `@echo "Downloading latest minishift binary at $(BIN_DIR)/minishift"`. This one is not required.

2017-09-27 07:22 UTC, budhrg commented on Makefile
> +	@echo "Moving minishift binary to $(BIN_DIR)"
@anjannath , CI is also failing. The another cd to $(BIN_DIR) is not working fine. Check

2017-09-27 07:43 UTC, budhrg commented on Makefile
> +	mv $(MINISHIFT_UNTAR_DIR)/minishift .
:+1:  This should work.

2017-09-27 09:36 UTC, budhrg commented
@anjannath , Please update the commit message with capitalized issue `Issue #...`.

2017-10-09 19:56 UTC, anjannath commented
Sorry @budhrg i havn't been watching this repo, so missed the comment, updating now.

2017-10-10 05:31 UTC, budhrg commented
retest this please

2017-10-10 05:33 UTC, budhrg commented
@anjannath , need rebase.

2017-10-10 10:59 UTC, anjannath commented
@budhrg I have no idea why its failing. Please have a look when you get time.

2017-10-11 17:03 UTC, budhrg commented
retest this please

2017-10-12 06:36 UTC, brgnepal approved these changes

2017-10-12 06:42 UTC, budhrg commented
Merged and thanks.

2017-10-12 06:42 UTC, closed without merging